### ISSUE TITLE
'Guard' Body Error

### ISSUE THREAD

**Issue by jlunardini** [muxinc/swift-upload-sdk#113]
hello!

just wanted to let you know I am getting an error ''guard' body must not fall through, consider using a 'return' or 'throw' to exit the scope' when attempting to archive my app using Xcode 16. 

MuxUploadSDK - DirectUpload+AVFoundation.swift

![CleanShot 2024-06-19 at 20 34 41@2x](https://github.com/muxinc/swift-upload-sdk/assets/48002540/89486538-b44a-4671-afa5-26b4f8f6986d)

**Comment by andrewjl-mux** [comment]
Hey @jlunardini, thanks for filing this! 

We'll release a patch for this later this week. The most likely cause here is the Swift optimizer eliding `precondition` when compiling in release mode.
